name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Supabase CLI without Docker
      - name: Install Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/download/v1.143.2/supabase_1.143.2_linux_amd64.tar.gz | tar xz
          sudo mv supabase /usr/local/bin/supabase
        # (Alternatively use setup-cli@v1, but this ensures latest and avoids Docker)

      # Run local sync script (bolt → supabase/functions)
      - name: Sync Bolt functions to Supabase folder
        run: npm run prepare-deploy

      # Deploy function to Supabase
      - name: Deploy create-payment-intent function
        run: supabase functions deploy create-payment-intent --project-ref utjgpehbaarrrhixebil --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
